/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ReserveDTO {
  multi?: boolean;
  phoneNumber?: string;
  reserverName?: string;
}
