/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type RoomsReservationsDTOType = typeof RoomsReservationsDTOType[keyof typeof RoomsReservationsDTOType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoomsReservationsDTOType = {
  PLAYSTATION_ROOM: 'PLAYSTATION_ROOM',
  PLAYSTATION_PARTITION: 'PLAYSTATION_PARTITION',
  BILLIARD: 'BILLIARD',
  HOCKEY: 'HOCKEY',
} as const;
