/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type RoomDTOType = typeof RoomDTOType[keyof typeof RoomDTOType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoomDTOType = {
  PLAYSTATION_ROOM: 'PLAYSTATION_ROOM',
  PLAYSTATION_PARTITION: 'PLAYSTATION_PARTITION',
  BILLIARD: 'BILLIARD',
  HOCKEY: 'HOCKEY',
} as const;
