/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RoomType } from './roomType';

export interface Room {
  available?: boolean;
  id?: number;
  name?: string;
  priceMulti?: number;
  priceSingle?: number;
  type?: RoomType;
}
