/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type RoomType = typeof RoomType[keyof typeof RoomType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoomType = {
  PLAYSTATION_ROOM: 'PLAYSTATION_ROOM',
  PLAYSTATION_PARTITION: 'PLAYSTATION_PARTITION',
  BILLIARD: 'BILLIARD',
  HOCKEY: 'HOCKEY',
} as const;
